export default {
    SEARCH_MOVIES_SUCCESS: 'SEARCH_MOVIES_SUCCESS',
    GET_MOVIE_SUCCESS: 'GET_MOVIE_SUCCESS',
    CLEAR_ACTIVE_MOVIE: 'CLEAR_ACTIVE_MOVIE',

    BEGIN_AJAX_CALL: 'BEGIN_AJAX_CALL',
    AJAX_CALL_ERROR: 'AJAX_CALL_ERROR'
};